# -*- coding: utf-8 -*-
{
    'name': "Visa",
    'version': '17.0',
    'category': 'Visa',
    'description': """ It is a Visa Module """,
    'sequence': -101,
    'author': 'Keval',
    'website': 'www.visa.com',
    'summary': 'For visa application devlopment',
    'depends': ['sale', 'l10n_in_sale', 'mail', 'stock', 'mrp', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/visa_security.xml',
        'report/pdf_report.xml',
        'report/pdf_report_2.xml',
        'report/client_xlsx_report.xml',
        'wizard/appointment.xml',
        'wizard/task.xml',
        'wizard/excel_wizard.xml',
        'wizard/select_record_view.xml',
        'wizard/Project_view.xml',
        'views/client_view.xml',
        'views/type.xml',
        'views/inherit.xml',
        'views/res_config_setting_view.xml',
        'views/menufacture_view.xml',
        'data/visamail.xml',
        'data/sequence.xml',
        'data/visa_client_data.xml',
        'data/server_action.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
